name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install  # This example project is built using npm and outputs the result . Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn ci

      - name: Install Node.js dependencies in CLIENT
        working-directory: ./client
        run: yarn install && yarn run typedoc

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./client/docs # The folder the action should deploy.